# Generated by Django 4.2.4 on 2023-09-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSE_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssedatapoint',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='ssedatapoint',
            name='current',
        ),
    ]
