# Generated by Django 4.2.4 on 2023-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('capacity_mw', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('primary_fuel', models.CharField(max_length=20)),
            ],
        ),
    ]
