# Generated by Django 4.2.4 on 2023-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('temperature_c', models.FloatField()),
                ('temperature_f', models.FloatField()),
                ('is_day', models.BooleanField()),
                ('condition_text', models.CharField(max_length=100)),
                ('wind_mph', models.FloatField()),
                ('wind_kph', models.FloatField()),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('pressure_mb', models.FloatField()),
                ('pressure_in', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('precip_in', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('feelslike_c', models.FloatField()),
                ('feelslike_f', models.FloatField()),
                ('vis_km', models.FloatField()),
                ('vis_miles', models.FloatField()),
                ('uv', models.FloatField()),
                ('gust_mph', models.FloatField()),
                ('gust_kph', models.FloatField()),
            ],
        ),
    ]
