# Generated by Django 4.2.4 on 2023-08-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Whether_report_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
