# Generated by Django 4.2.4 on 2023-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSE_DATA_STORE_AND_SHOW_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssedatapoint',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ssedatapoint',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ssedatapoint',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
